server {
    listen 80;
    server_name noxara.page www.noxara.page;
    root /www/wwwroot/noxara.page;
    index index.php index.html;

    location / { try_files $uri $uri/ /index.php?$query_string; }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/tmp/php-cgi-82.sock;
    }

    location ~* ^/(config|includes|actions|database|cron|storage|nginx)/ {
        deny all;
        return 403;
    }

    location ~* \.(sql|log|env|bak|backup|ini|conf|sh)$ {
        deny all;
        return 403;
    }

    location ~ /\. {
        deny all;
        return 403;
    }

    location ~* ^/uploads/.*\.php$ {
        deny all;
        return 403;
    }
}
